In [1]:
import json
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow.keras as keras

DATASET_PATH = "data.json"
# DATASET_PATH = "data_full.json"

def load_data(dataset_path):
    with open(dataset_path, "r") as fp:
        data = json.load(fp)
        
    # convert numpy arrays into numpy arrays
    inputs = np.array(data["mfcc"])
    targets = np.array(data["labels"])
    
    return inputs, targets


In [2]:
if __name__ == "__main__":
        
    # load data
    inputs, targets = load_data(DATASET_PATH)
    
    # split the data into train and test sets
    inputs_train, inputs_test, targets_train, targets_test = train_test_split(inputs, targets, test_size = 0.3)
    
    # build the network architecture
    model = keras.Sequential([
        # input layer
        keras.layers.Flatten(input_shape = (inputs.shape[1], inputs.shape[2])),
        
        # 1st hidden layer
        keras.layers.Dense(512, activation = "relu"),
        
        # 2nd hidden layer
        keras.layers.Dense(256, activation = "relu"),
        
        # 3rd hidden layer
        keras.layers.Dense(64, activation = "relu"),
        
        # output layer
        keras.layers.Dense(10, activation = "softmax")
    ])
    
    # compile network
    optimizer = keras.optimizers.Adam(learning_rate = 0.0001)
    model.compile(optimizer = optimizer, loss = "sparse_categorical_crossentropy", metrics = ["accuracy"])
    model.summary()
    
    # train network
    model.fit(inputs_train, targets_train, validation_data = (inputs_test, targets_test), epochs = 100, batch_size = 32)
    

2024-11-09 22:12:54.782379: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-09 22:12:54.794464: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-09 22:12:54.794946: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 13)                0         
                                                                 
 dense (Dense)               (None, 512)               7168      
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 64)                16448     
                                                                 
 dense_3 (Dense)             (None, 10)                650       
                                                                 
Total params: 155,594
Trainable params: 155,594
Non-trainable params: 0
_________________________________________________________________


2024-11-09 22:12:54.796210: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-09 22:12:54.840193: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-09 22:12:54.841322: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-09 22:12:54.842105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built witho

Epoch 1/100
3/3 [==============================] - 1s 59ms/step - loss: 12.8576 - accuracy: 0.1571 - val_loss: 6.6855 - val_accuracy: 0.1667
Epoch 2/100
3/3 [==============================] - 0s 15ms/step - loss: 7.2682 - accuracy: 0.1429 - val_loss: 5.4523 - val_accuracy: 0.1333
Epoch 3/100
1/3 [=========>....................] - ETA: 0s - loss: 6.4854 - accuracy: 0.0312

2024-11-09 22:12:57.052774: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


3/3 [==============================] - 0s 14ms/step - loss: 5.9602 - accuracy: 0.0714 - val_loss: 4.1287 - val_accuracy: 0.2667
Epoch 4/100
3/3 [==============================] - 0s 14ms/step - loss: 4.4739 - accuracy: 0.1571 - val_loss: 2.7421 - val_accuracy: 0.3333
Epoch 5/100
3/3 [==============================] - 0s 14ms/step - loss: 2.9567 - accuracy: 0.2286 - val_loss: 1.8868 - val_accuracy: 0.5333
Epoch 6/100
3/3 [==============================] - 0s 13ms/step - loss: 2.0354 - accuracy: 0.3429 - val_loss: 2.3379 - val_accuracy: 0.3667
Epoch 7/100
3/3 [==============================] - 0s 13ms/step - loss: 2.0916 - accuracy: 0.3143 - val_loss: 2.4312 - val_accuracy: 0.3333
Epoch 8/100
3/3 [==============================] - 0s 13ms/step - loss: 1.9860 - accuracy: 0.4000 - val_loss: 1.9967 - val_accuracy: 0.4000
Epoch 9/100
3/3 [==============================] - 0s 13ms/step - loss: 1.5885 - accuracy: 0.4571 - val_loss: 1.5622 - val_accuracy: 0.5000
Epoch 10/100
3/3 [==============

3/3 [==============================] - 0s 14ms/step - loss: 0.2785 - accuracy: 0.9571 - val_loss: 0.4377 - val_accuracy: 0.8667
Epoch 62/100
3/3 [==============================] - 0s 14ms/step - loss: 0.2882 - accuracy: 0.9429 - val_loss: 0.4284 - val_accuracy: 0.9000
Epoch 63/100
3/3 [==============================] - 0s 15ms/step - loss: 0.2725 - accuracy: 0.9571 - val_loss: 0.3798 - val_accuracy: 0.8333
Epoch 64/100
3/3 [==============================] - 0s 14ms/step - loss: 0.2704 - accuracy: 0.9429 - val_loss: 0.3820 - val_accuracy: 0.8667
Epoch 65/100
3/3 [==============================] - 0s 12ms/step - loss: 0.2743 - accuracy: 0.9143 - val_loss: 0.3562 - val_accuracy: 0.8333
Epoch 66/100
3/3 [==============================] - 0s 15ms/step - loss: 0.2519 - accuracy: 0.9571 - val_loss: 0.3677 - val_accuracy: 0.8000
Epoch 67/100
3/3 [==============================] - 0s 17ms/step - loss: 0.2520 - accuracy: 0.9571 - val_loss: 0.3875 - val_accuracy: 0.8000
Epoch 68/100
3/3 [========

In [3]:
model((inputs[0].reshape(1,1,13)))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]], dtype=float32)>

In [4]:
inputs[0].reshape(1,1,13)

array([[[-247.5295105 ,   79.69992065,   15.64183998,    7.84844398,
           11.53348732,   -0.75775474,    4.80943012,    1.19679379,
           -7.02707481,    5.63072252,   -5.95659924,   -3.6491735 ,
           -7.93608856]]])

In [19]:
DATASET_PATH = "data.json"

# load data
inputs, targets = load_data(DATASET_PATH)

# split the data into train and test sets
inputs_train, inputs_test, targets_train, targets_test = train_test_split(inputs, targets, test_size = 0.3)

# build the network architecture
model = keras.Sequential([
    # input layer
    keras.layers.Flatten(input_shape = (inputs.shape[1], inputs.shape[2])),

    # 1st hidden layer
    keras.layers.Dense(512, activation = "relu"),

    # 2nd hidden layer
    keras.layers.Dense(256, activation = "relu"),

    # 3rd hidden layer
    keras.layers.Dense(64, activation = "relu"),

    # output layer
    keras.layers.Dense(10, activation = "softmax")
])

In [23]:
targets_test

array([1, 4, 1, 0, 2, 9, 6, 7, 0, 2, 9, 6, 9, 6, 5, 2, 2, 3, 3, 2, 8, 6,
       8, 3, 7, 5, 0, 9, 1, 9])

In [20]:
inputs

array([[[-2.47529510e+02,  7.96999207e+01,  1.56418400e+01, ...,
         -5.95659924e+00, -3.64917350e+00, -7.93608856e+00]],

       [[-2.31200180e+02,  5.82810669e+01,  1.79094391e+01, ...,
          5.95300007e+00,  7.44017458e+00,  5.23655033e+00]],

       [[-2.45812866e+02,  6.53213654e+01,  7.87117290e+00, ...,
         -1.10102761e+00,  1.67966020e+00,  1.26937714e+01]],

       ...,

       [[-1.39372025e+02,  1.75213318e+01, -1.65865326e+01, ...,
          1.65087547e+01,  7.03052139e+00, -4.86146879e+00]],

       [[-1.62188293e+02,  1.14621239e+01, -1.89034386e+01, ...,
          1.55379906e+01, -1.87734652e+00, -1.75499454e-01]],

       [[-1.12497108e+02,  5.74599409e+00, -2.65631027e+01, ...,
          1.81796570e+01,  6.24819899e+00,  2.66163301e+00]]])

In [22]:
model((inputs[0].reshape(1,1,13)))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.4822620e-08, 1.3891843e-11, 8.8116203e-06, 9.1402608e-11,
        2.9917704e-08, 1.1092133e-12, 9.9997938e-01, 1.2898852e-15,
        1.0954515e-10, 1.1804933e-05]], dtype=float32)>

In [21]:
inputs.shape

(100, 1, 13)

In [10]:
targets[0]

0

In [4]:
targets

array([ 0,  0,  0, ..., 10, 10, 10])